In [14]:
import numpy as np
from itertools import product

def create_mask(feature_num, exclude_feature=None):
    """
    Generate and return the coalition matrix of size 2^feature_num, excluding 
    coalitions where the specified feature (exclude_feature) appears.
    """
    
    # Generate the coalition matrix
    mask = np.array(list(product(range(2), repeat=feature_num)))
    
    # Remove the all-zero and all-one coalitions
    mask = mask[~np.all(mask == 0, axis=1)]
    mask = mask[~np.all(mask == 1, axis=1)]
    
    # If exclude_feature is specified, remove all coalitions where this feature appears
    if exclude_feature is not None and 0 <= exclude_feature < feature_num:
        mask = mask[mask[:, exclude_feature] == 0]
    
    return mask


In [15]:
mask = create_mask(16, 0)

In [16]:
mask

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 1],
       ...,
       [0, 1, 1, ..., 1, 0, 1],
       [0, 1, 1, ..., 1, 1, 0],
       [0, 1, 1, ..., 1, 1, 1]])

In [17]:
len(mask)

32767

In [18]:
mask[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [21]:
mask[32766]

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [22]:
import numpy as np
from itertools import product

def create_mask(feature_num, exclude_feature=None):
    """
    Generate and return the coalition matrix of size 2^feature_num, excluding 
    coalitions where the specified feature (exclude_feature) appears. If feature_num
    is greater than 10, randomly sample 2^10 coalitions from the final matrix.
    """
    max_feature_num = 10
    sample_size = 2 ** max_feature_num

    # Generate the coalition matrix
    mask = np.array(list(product(range(2), repeat=feature_num)))
    
    # Remove the all-zero and all-one coalitions
    mask = mask[~np.all(mask == 0, axis=1)]
    mask = mask[~np.all(mask == 1, axis=1)]
    
    # If exclude_feature is specified, remove all coalitions where this feature appears
    if exclude_feature is not None and 0 <= exclude_feature < feature_num:
        mask = mask[mask[:, exclude_feature] == 0]

    # If feature_num is greater than max_feature_num, randomly sample 2^max_feature_num coalitions
    if feature_num > max_feature_num:
        if mask.shape[0] > sample_size:
            #np.random.seed(42)  # If we want to get the same results every time we run the code
            mask = mask[np.random.choice(mask.shape[0], sample_size, replace=False)]
        else:
            print(f"Warning: The number of available coalitions ({mask.shape[0]}) is less than {sample_size}.")
    
    return mask


In [32]:
mask2 = create_mask(16, 0)

In [33]:
mask2

array([[0, 0, 1, ..., 1, 0, 0],
       [0, 0, 1, ..., 1, 0, 1],
       [0, 1, 1, ..., 1, 0, 1],
       ...,
       [0, 1, 0, ..., 1, 1, 1],
       [0, 1, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 0, 1]])

In [34]:
len(mask2)

1024

In [35]:
mask2[0]

array([0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0])

In [36]:
mask2[1023]

array([0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1])